name: Sync Rules to Stash

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  process-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up directories
      run: |
        mkdir -p Stash/Auto

    - name: Process Rules/*.txt → Stash/
      run: |
        for src in Rules/*.txt; do
          dest="Stash/$(basename "$src")"
          sed '/^  - DOMAIN-REGEX,/d' "$src" > "$dest"
        done

    - name: Process Rules/Auto/*.txt → Stash/Auto/
      run: |
        for src in Rules/Auto/*.txt; do
          dest="Stash/Auto/$(basename "$src")"
          sed '/^  - DOMAIN-REGEX,/d' "$src" > "$dest"
        done

    - name: Show processed files
      run: |
        echo "Processed files:"
        find Stash -type f

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add -f Stash/** Rules/**
        git commit -m "Sync processed rules to Stash"
        git push
      continue-on-error: true
